name: complete
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-0 <4.0.0'

dependencies:
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  firebase_ui_auth: ^1.14.0
  firebase_ui_oauth_google: ^1.3.2
  cloud_firestore: ^5.2.0
  firebase_messaging: ^15.0.4
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/default_avatar.png
  - assets/penguin_icon.jpg
