// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions firebaseOptions = FirebaseOptions(
      apiKey: "AIzaSyCqFjCV_9CZmYeIvcK9FVy4drmKUlSaIWY",
      authDomain: "flutterfire-ui-codelab.firebaseapp.com",
      projectId: "flutterfire-ui-codelab",
      storageBucket: "flutterfire-ui-codelab.appspot.com",
      messagingSenderId: "963656261848",
      appId: "1:963656261848:web:7219f7fca5fc70afb237ad",
      measurementId: "G-DGF0CP099H");
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoWuLcazges59i3zdtZabyF22I6Ob5GYc',
    appId: '1:491265368461:web:21dd9ed8cb4b02d4095dc4',
    messagingSenderId: '491265368461',
    projectId: 'hadlittlecircle',
    authDomain: 'hadlittlecircle.firebaseapp.com',
    storageBucket: 'hadlittlecircle.appspot.com',
  );

  // Generate this file with credentials with the FlutterFire CLI

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWA7uGA5A38rM0JVJ1vMRZ58fc0v02auM',
    appId: '1:491265368461:android:133c86e42c075b53095dc4',
    messagingSenderId: '491265368461',
    projectId: 'hadlittlecircle',
    storageBucket: 'hadlittlecircle.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBFw74mWhrmGVsixIVIwgtng7Hg7BKM2Q',
    appId: '1:491265368461:ios:d615230f96cf1368095dc4',
    messagingSenderId: '491265368461',
    projectId: 'hadlittlecircle',
    storageBucket: 'hadlittlecircle.appspot.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBFw74mWhrmGVsixIVIwgtng7Hg7BKM2Q',
    appId: '1:491265368461:ios:d615230f96cf1368095dc4',
    messagingSenderId: '491265368461',
    projectId: 'hadlittlecircle',
    storageBucket: 'hadlittlecircle.appspot.com',
    iosBundleId: 'com.example.complete',
  );
}
